M48
; DRILL file {KiCad 7.0.10} date Wed Mar 13 20:42:54 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-13T20:42:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X137.795Y-75.438
X137.795Y-99.314
X157.607Y-75.438
X157.607Y-99.314
M30
